name: Check PR Branch

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@1.2.0
        id: PR
        name: Fetch PR information
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
      - name: Filter PR information
        if: success() && steps.PR.outputs.number
        env:
          prJSON: ${{ steps.PR.outputs.pr }}
          prFrom: ${{steps.PR.outputs.pr.head.ref}}
          prTo: ${{steps.PR.outputs.pr.base.ref}}
          prTitle: ${{ steps.PR.outputs.pr_title }}
      - run: echo PR "$prTitle" wants to merge $prFrom into $prTo