name: Check PR Branch

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check master constraint
        if: ${{ env.GITHUB_BASE_REF == 'master' }}
        run: export VALID_PR=$($GITHUB_HEAD_REF=="hotfix")
      - name: check unexpected branch
        if: ${{ env.GITHUB_BASE_REF != 'master' }}
        run: echo $GITHUB_BASE_REF is not a supported target branch