name: Check PR

on:
  pull_request:
    types: [ opened, reopened, edited ]
    branches:
      - master
      - main
      - staging
  pull_request_target:
    types: [ opened, reopened, edited ]
    branches:
      - dev
      - hotfix

jobs:
  branching-check:
    name: Check Branching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check fork
        if: github.event.pull_request.head.repo.full_name != github.repository && github.actor != 'dependabot[bot]' && github.base_ref != 'dev' && github.base_ref != 'hotfix'
        run: |
          echo "::error::Forks are only allowed to merge into \`dev\` or \`hotfix\`"
          exit 1
      - name: Check master branch
        id: master_check
        uses: ./.github/actions/branch-check
        if: ${{ github.base_ref=='master' || github.base_ref=='main' }}
        with:
          allowedBranches: hotfix|documentation|staging
      - name: Check staging branch
        id: staging_check
        uses: ./.github/actions/branch-check
        if: ${{ github.base_ref=='staging' }}
        with:
          allowedBranches: hotfix|dev
      - name: Check dev branch
        id: dev_check
        uses: ./.github/actions/branch-check
        if: ${{ github.base_ref=='dev' }}
        with:
          allowedBranches: feat\/.+|hotfix|bugfix\/.+ #this is a regex
      - name: check hotfix branch
        id: hotfix_check
        uses: ./.github/actions/branch-check
        if: ${{ github.base_ref=='hotfix' }}
        with:
          allowedBranches: bugfix\/.+
      - name: Add master branch message
        if: failure() && (steps.master_check.outcome == 'failure')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.master_check.outputs.errorMessage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add staging branch message
        if: failure() && (steps.staging_check.outcome == 'failure')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.staging_check.outputs.errorMessage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add dev branch message
        if: failure() && (steps.dev_check.outcome == 'failure')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.dev_check.outputs.errorMessage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add hotfix branch message
        if: failure() && (steps.hotfix_check.outcome == 'failure')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.hotfix_check.outputs.errorMessage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Label PR
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Invalid']
            })
      - name: Close PR
        if: failure()
        uses: superbrothers/close-pull-request@v3
